### ISSUE TITLE
currentPage starts from 0

### ISSUE THREAD

**Issue by airfortech** [thijssmudde/react-headless-pagination#2]
`currentPage` counts from `0` but displays `1` or am I doing something wrong?

**Comment by Ding-Fan** [comment]
I'm happy with it. It's easier for me to `slice` my `dataList`

**Comment by thijssmudde** [comment]
@airfortech most other paginate libraries also start at 0 for the first page. If you mean the "Pagination" story, the currentPage is added with 1.

**Comment by greenymcgee** [comment]
I love everything about this library except for this problem. From what I can tell, 0 is not the convention and I'm having to fight against the first page being 0 to get anything to work with any backend pagination libraries. I'm starting to think that the only way I'll get anything to work is by either hacking a solution in the frontend or the back, and neither option is good. The only great option might be to not use this library which is really a bummer because I do really like it.
